### ISSUE TITLE
Inconsistent file names in 'readme.md'

### ISSUE THREAD

**Issue by vixOnTest** [andrey-stepantsov/j-dump2csv#1]
`Input CSV file (test.csv)` does not correspond with SQL query: 
```
dbtype: H2
uri: "jdbc:h2:mem:"
database: test
query: |-
  SELECT * FROM CSVREAD('sample.csv') WHERE CODE like '%1';
output_format: CSV
```
Observe: There are different file names, 'test.csv' and 'sample.csv' - It should be the same file name.

**Comment by andrey-stepantsov** [comment]
@vixOnTest , please, fix 'readme.md'
